// app/layout.tsx (RootLayout)
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/ui/SideBar";
import Header from "@/components/Header";
import { Suspense } from "react";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <Header />

        {/* Floating sidebar that does NOT shift the main content */}
        {/* If your Header is sticky and ~64px tall, use top-16. Adjust as needed. */}
        <aside
          className="
            fixed left-0 top-16 z-40 hidden lg:block
            h-[calc(100vh-4rem)] w-72
            overflow-y-auto bg-background/80
            backdrop-blur supports-[backdrop-filter]:bg-background/60
          "
          aria-label="Sidebar navigation"
        >
          <Sidebar />
        </aside>

        {/* Main stays centered, unaffected by the sidebar */}
        <main className="relative min-h-screen w-full flex justify-center">
          {/* Centered page container */}
          <div className="w-full max-w-7xl px-3 sm:px-4 lg:px-8">
            <Suspense
              fallback={
                <div className="py-8">
                  <div className="animate-pulse space-y-4">
                    <div className="h-6 w-40 rounded bg-muted/50" />
                    <div className="h-10 w-2/3 rounded bg-muted/40" />
                    <div className="h-40 rounded bg-muted/30" />
                  </div>
                </div>
              }
            >
              {children}
            </Suspense>
          </div>
        </main>
      </body>
    </html>
  );
}
